# Generated by Django 2.2.1 on 2019-05-19 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190519_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 18, 27, 58, 26373)),
            preserve_default=False,
        ),
    ]
