# Generated by Django 2.2.1 on 2019-05-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
    ]
