# Generated by Django 2.2.1 on 2019-06-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190611_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='intrested_in',
            new_name='interested_in',
        ),
    ]
