# Generated by Django 2.2.1 on 2019-06-27 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190611_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='interested_in',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='myapp.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
