# Generated by Django 2.2.1 on 2019-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190627_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='profile_pictures/None.jpg', upload_to='profile_pictures'),
        ),
    ]
