# Generated by Django 2.2.1 on 2019-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='profile_pictures/None.jpg', upload_to='profile_pictures'),
        ),
    ]
